import type { Metadata } from "next";
import { Inter } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });
const clashGrotesk = localFont({
  src: [
    {
      path: './../../public/fonts/ClashGrotesk-Bold.otf',
      weight: '600',
      style: 'semibold',
    },
    {
      path: './../../public/fonts/ClashGrotesk-Regular.otf',
      weight: '400',
      style: 'regular',
    },
    {
      path: './../../public/fonts/ClashGrotesk-Medium.otf',
      weight: '500',
      style: 'medium',
    },
    {
      path: './../../public/fonts/ClashGrotesk-Light.otf',
      weight: '300',
      style: 'light',
    },
    {
      path: './../../public/fonts/ClashGrotesk-Extralight.otf',
      weight: '200',
      style: 'extralight',
    },
    {
      path: './../../public/fonts/ClashGrotesk-Semibold.otf',
      weight: '600',
      style: 'bold',
    },
  ],
})

export const metadata: Metadata = {
  title: "News App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={clashGrotesk.className} >
        <div className="mx-auto max-w-5xl my-16">
          {children}
        </div>
      </body>
    </html>
  );
}
